export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"


export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"


export const ANALYSE_REQUEST = "ANALYSE_REQUEST"
export const ANALYSE_SUCCESS = "ANALYSE_SUCCESS"
export const ANALYSE_FAILURE = "ANALYSE_FAILURE"


export const LOGOUT = "LOGOUT"